import operator
from typing import Annotated, TypedDict, Optional

# GraphState 상태 정의
class CanonState(TypedDict):
    question: Annotated[str, "Question"] # parentgraph 공유
    brand: Annotated[Optional[str],"brandname"]
    model: Annotated[Optional[str],"modelname"]
    transform_question: Annotated[list, "Transformed queries generated by LLM"]
    multi_context: Annotated[list[str], operator.add]
    ensemble_context: Annotated[str, "Ensemble_context"]
    filtered_context: Annotated[str, "Filtering Context"]
    context: Annotated[str, "Context"]  # parentgraph 공유
    answer: Annotated[str, "Answer"]  # parentgraph 공유
    sessionId: int
    messageId: int

class QueryState(TypedDict):
    query: str
